### ISSUE TITLE
npm install errors since 25-10-2016

### ISSUE THREAD

**Issue by Vasileios80** [boundlessgeo/sdk#232]
Hello,
I have a constant issue with the boundless sdk during the installation of dependencies.
I didn't have that issue about 24 hours ago. Is there any solution? Am I doing something wrong? 
[npm-debug.txt](https://github.com/boundlessgeo/sdk/files/553003/npm-debug.txt)
Thx in advance
V.

**Comment by bartvde** [comment]
thanks, got another report on this as well, working on a fix now

**Comment by bartvde** [comment]
Should be fixed with 0.9.7 which I just published now, can you check?

**Comment by Vasileios80** [comment]
Just checked the same issue, Sorry.
[npm-debug.txt](https://github.com/boundlessgeo/sdk/files/553090/npm-debug.txt)

**Comment by bartvde** [comment]
I see you are on Windows, I tested on Mac. Does it work with 0.9.5 then?

**Comment by bartvde** [comment]
I'm going to check in a Windows VM soon

**Comment by bartvde** [comment]
I guess this started happening when I changed the postinstall task with https://github.com/boundlessgeo/sdk/commit/f50e0905e7dc5b8466519702e5d739b0ee5a924e I'm going to revert this change and handle it differently

**Comment by bartvde** [comment]
ok fixed with 0.9.8 and verified in a Windows VM, sorry for the inconvenience

**Comment by Vasileios80** [comment]
Thanks a lot, all are working smooth again, great job!!!
