### ISSUE TITLE
Make options in feature table collapsible

### ISSUE THREAD

**Issue by bartvde** [boundlessgeo/sdk#271]

**Comment by milafrerichs** [comment]
maybe reduce the whitespace a bit more.
it is also very small. should be bigger, right?

**Comment by bartvde** [comment]
Right, normally material-ui sizes automatically, but because I size the table to the available content, it probably doesn't kick in.

**Comment by bartvde** [comment]
It seems positionDialog of the material-ui dialog gets called before the table has height and content

**Comment by bartvde** [comment]
I'm guessing since height of the table is not in the state, it's determined in render, it doesn't trigger componentDidUpdate

**Comment by bartvde** [comment]
The achieve the collapse we can use a Card, but first we need to solve the height / position issue, tricky one

http://www.material-ui.com/#/components/card

**Comment by bartvde** [comment]
see also: https://github.com/callemall/material-ui/issues/5471

**Comment by bartvde** [comment]
there is also the issue that the dialog increases in length with every time a paging button is pressed
