### ISSUE TITLE
can't get EditPopup working

### ISSUE THREAD

**Issue by hishamkaram** [boundlessgeo/sdk#299]
- in jsx file 
`<div><EditPopup map={map}/></div>`
but when i click on feature in the map style changed to `display: none;`
![html in browser capture](https://cloud.githubusercontent.com/assets/24391550/21389269/78593aba-c789-11e6-9b71-ed73314c0bab.PNG)

how can i get it working ?

**Comment by bartvde** [comment]
Are you using it on a local vector layer? It only works on those currently?

**Comment by bartvde** [comment]
I do see a few UI/UX issues on it in my test now (I'll tackle those soon), but it does display.


![screen shot 2016-12-21 at 13 34 21](https://cloud.githubusercontent.com/assets/319678/21389465/33e53b7e-c782-11e6-84cf-48b2c9893a16.png)

**Comment by hishamkaram** [comment]
i am using it on map comes from geoserver

**Comment by bartvde** [comment]
yes but what type of source does your layer have? It needs ```ol.source.Vector```

**Comment by hishamkaram** [comment]
got it thank you . i will try it

**Comment by bartvde** [comment]
I should extend the functionality so you can use it on WMS as well, will add that to my list

**Comment by hishamkaram** [comment]
this is the current layer
![capture](https://cloud.githubusercontent.com/assets/24391550/21389641/6a9475b4-c78b-11e6-9257-648d9bfb673b.PNG)

**Comment by bartvde** [comment]
yeah that looks like WMS

**Comment by hishamkaram** [comment]
not working :(

**Comment by bartvde** [comment]
If you add the layer using WFS it should work:

![screen shot 2016-12-21 at 13 42 10](https://cloud.githubusercontent.com/assets/319678/21389710/4e9c9f7e-c783-11e6-8d0d-4bc89b32b007.png)

**Comment by hishamkaram** [comment]
one minute please i am trying

**Comment by hishamkaram** [comment]
nothing changed .

**Comment by bartvde** [comment]
Can you see if it works for you when using the QuickView app and changing the InfoPopup tag to EditPopup?

https://github.com/boundlessgeo/sdk-apps/tree/master/quickview

**Comment by hishamkaram** [comment]
i cannot build this app on my machine i use `https://boundlessgeo.github.io/sdk/dist/js/full.js` to run this components

**Comment by bartvde** [comment]
can you share your full app then maybe? Or provide a jsFiddle to reproduce?

**Comment by bartvde** [comment]
I fixed the positioning bug with: https://github.com/boundlessgeo/sdk/commit/6ca916729fed3fa7da23a008e3849c322f7890c0 the UI/UX issues were because of the application specific css in QuickView (where EditForm is in a tab), out of the box it works fine:

![screen shot 2016-12-21 at 15 17 44](https://cloud.githubusercontent.com/assets/319678/21392563/c0ce9130-c790-11e6-9b70-0ff8ed1e21b4.png)

**Comment by hishamkaram** [comment]
it's a huge django-app cannot provide JsFiddle please take a look on these files (2 files) [link](https://ufile.io/bcb82)

**Comment by bartvde** [comment]
I looked at the files but they don't give me a clue. I assume your django-app cannot be seen online?

**Comment by bartvde** [comment]
Also how are you loading your layers? From GeoNode through the GXP based config format?

**Comment by hishamkaram** [comment]
```
config.map.layers.forEach(function (layerConfig) {
            //var layerConfig = config.map.layers[i];
            var layerSourceConfig = config.sources[layerConfig.source];
            var layer = null;
            if (layerSourceConfig.ptype == 'gxp_olsource') {
                layer = getTileLayer(layerConfig);
            }
            else if (layerSourceConfig.ptype == 'gxp_osmsource') {
                layer = getTileLayer(layerConfig, new ol.source.OSM());
            } else if (layerSourceConfig.ptype === 'gxp_mapquestsource') {
                layer = getTileLayer(layerConfig, new ol.source.MapQuest({
                    layer: layerConfig.name == 'naip' ? 'sat' : 'osm'
                }));
            } else if (layerSourceConfig.ptype === 'gxp_wmscsource') {
                var layerSource = new ol.source.TileWMS({
                    url: layerSourceConfig.url,
                    params: {
                        LAYERS: layerConfig.name,
                        //VERSION: '1.1.1',
                        TILED: true,
                        STYLES: layerConfig.styles,
                        FORMAT: layerConfig.format,
                        TRANSPARENT: layerConfig.transparent
                    }
                    //,
                    // tileLoadFunction:function(imageTile, src) {
                    //
                    //     var extent     = map.olMap.getView().calculateExtent(map.olMap.getSize());
                    //     //extent      = ol.proj.transformExtent(extent, 'EPSG:3857', 'EPSG:4326');
                    //     var coordinates = ol.extent.getBottomLeft(extent);
                    //     imageTile.getImage().src = src + "&TILESORIGIN=" + coordinates[0] + "," + coordinates[1];
                    //     console.debug(imageTile.getImage());
                    //     console.debug(imageTile.getImage().src);
                    // }
                });
                layer = getTileLayer(layerConfig, layerSource);
            }
```

**Comment by bartvde** [comment]
Yeah as I said this doesn't work on ```ol.source.TileWMS``` currently

**Comment by hishamkaram** [comment]
thank you very much and  i tried your example working fine. i hope `editpopup` support more types soon

**Comment by bartvde** [comment]
hopefully I'll add that this week, will update GitHub issue when I do
