### ISSUE TITLE
Querybuilder Filter input not working on touch devices

### ISSUE THREAD

**Issue by hishamkaram** [boundlessgeo/sdk#310]
Querybuilder filter input not working on touch devices i.e cannot type into it 
tested on mobile device and with google deveoper tools also i tried `cursor: pointer; ` for body and root element
i found these issues [issue1](https://github.com/facebook/react/issues/1169) [issue2](https://github.com/facebook/react/issues/2055)  @bartvde 
![capture](https://cloud.githubusercontent.com/assets/24391550/21589013/b3979ad4-d0f5-11e6-9247-a5352d050ae4.PNG)

**Comment by bartvde** [comment]
I cannot reproduce this on my iPad with the updated basic example, which uses SDK 0.10.x and material-ui 0.16.x, what versions are you using?

**Comment by hishamkaram** [comment]
"boundless-sdk": "^0.10.10"

**Comment by hishamkaram** [comment]
Solved

**Comment by bartvde** [comment]
how did you solve it?

**Comment by hishamkaram** [comment]
@bartvde  it was an issue with jquery draggable but still not working fine with mobile chrome 
```
$("#query-panel").draggable();
        $("#query-panel input").click(function () {
            $(this).focus();
        });
```
