### ISSUE TITLE
AddLayerModal example or usage

### ISSUE THREAD

**Issue by hishamkaram** [boundlessgeo/sdk#323]
cannot use `AddLayerModal` component not in examples repo 
in jsx : 

```
<div><AddLayerModal ref="dialog_map" map={map} allowUserInput={true}
                                                    sources={[{
                                                        url: '/xxxx_proxy/http://localhost:4041/geoserver/wms',
                                                        type: 'WMS',
                                                        title: 'Local GeoServer'
                                                    }]}/></div>
```
in browser : 
`<div><div data-reactroot="" class="sdk-component add-layer-modal" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);position: fixed;box-sizing: border-box;z-index: 1500;top: 0px;left: -10000px;width: 100%;height: 100%;transition: left 0ms cubic-bezier(0.23, 1, 0.32, 1) 450ms;"><div></div><div style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); background-color: rgba(0, 0, 0, 0.541176); width: 100%; top: 0px; left: -100%; opacity: 0; height: 100%; position: fixed; will-change: opacity; transform: translateZ(0px); transition: left 0ms cubic-bezier(0.23, 1, 0.32, 1) 400ms, opacity 400ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; z-index: 1400;"><!-- react-empty: 4 --></div></div></div>`
what should i do to open modal or use it

**Comment by bartvde** [comment]
You will need to call the open function on it, see the LayerList code for an example

```
this.refs.addlayermodal.getWrappedInstance().open();
```

**Comment by hishamkaram** [comment]
thank you very much 👍
