### ISSUE TITLE
Cannot find module './node_modules/boundless-sdk/js/components/InfoPopup.jsx'

### ISSUE THREAD

**Issue by kwaabs** [boundlessgeo/sdk#384]
Hi,

It seems there has been a change in the directory structure.. there is no 'js' folder anymore.
Could you kindly check it? Or I am doing something wrong

**Comment by bartvde** [comment]
yes import paths have changed you need to use:

```import InfoPopup from 'boundless-sdk/components/InfoPopup';```

instead

**Comment by kwaabs** [comment]
@bartvde ohk.... I see. Fixed that, then this appears 
Cannot find module 'pui-react-buttons'
Unexpected token

(Palm in face)

**Comment by bartvde** [comment]
oh you're on an ancient version then, we switched to material-ui a long time ago

**Comment by kwaabs** [comment]
errrmm... i pulled it today... So how ancient are we talking about? BC? Dinosaur-age?
Can you just help me fix it? Pleeaase?

**Comment by bartvde** [comment]
More than a year ago. Can you tell me the steps you followed today then? I cannot understand how you would get to pui-react stuff.

**Comment by kwaabs** [comment]
well, I am following the steps in
https://connect.boundlessgeo.com/docs/suite/sdk/latest/

**Comment by bartvde** [comment]
what is the output for

```web-sdk -V``` ?

**Comment by kwaabs** [comment]
0.10.2
That is it
Is it current?

**Comment by bartvde** [comment]
yes that is current, is there anything in your app.jsx then that points to pui-react? When generating a new app you should get this: https://raw.githubusercontent.com/boundlessgeo/sdk-generator/master/templates/js/app.jsx

**Comment by kwaabs** [comment]
Errrm... NO.... that is not the current app.jsx but i've updated it with what you just gave me. It works.
Nothing is showing at localhost:3000 (it is blank)

**Comment by bartvde** [comment]
So what is in this file for you? ~/.nvm/versions/node/v6.9.2/lib/node_modules/boundless-web-sdk-generator/templates/js/app.jsx

Replace 6.9.2 with the version you're using.

What OS are you on btw?

**Comment by kwaabs** [comment]
Well, its not. I created an app using the plugin... Web app builder (boundless)
I am using using 6.0.0 ,Win 10.
Am I doing something wrong?

Like I said earlier, I followed the steps in https://connect.boundlessgeo.com/docs/suite/sdk/latest/

**Comment by bartvde** [comment]
Ah that explains it. Yeah then you probably have an outdated WAB. It's got a newer version on our dev plugin server, but I think we only provide that to customers. Let me check back.

**Comment by bartvde** [comment]
@kwaabs did you get the WAB plugin through connect? Do you have an account there and if so what type of account?

**Comment by kwaabs** [comment]
i've had it long ago late 2015/early 2016 there about (not too sure). boundless repository(qgis) am i supposed to pay for it?

**Comment by bartvde** [comment]
If you want to get a newer version of WAB, you will need to get a subscription of Boundless Desktop “Enterprise” for at least a month. If you want ongoing support (i.e after the first month), then you need to keep (or re-engage) your subscription.
