### ISSUE TITLE
Feature table not working with different layers

### ISSUE THREAD

**Issue by hishamkaram** [boundlessgeo/sdk#411]
this is the working [example](http://demo.cartoview.net/apps/cartoview_geonode_viewer/15/view/#map=9783.93962050256/2788689.17/1691082.89/0):
![screenshot from 2017-03-08 14-50-34](https://cloud.githubusercontent.com/assets/24391550/23704851/8536e83c-040f-11e7-9304-498125470c07.png)
this [example](http://demo.cartoview.net/apps/cartoview_geonode_viewer/14/view/#map=76.43702828517625/-8233682.17/4965608.48/0) not working:
![screenshot from 2017-03-08 14-52-36](https://cloud.githubusercontent.com/assets/24391550/23704807/542752f4-040f-11e7-9cd4-0cb9cbe4be8e.png)

in development:
![screenshot from 2017-03-08 14-53-25](https://cloud.githubusercontent.com/assets/24391550/23704877/9f1ed552-040f-11e7-93d9-30b6d0d41b1d.png)

**Comment by bartvde** [comment]
Looks to be something wrong with your GML, look at the srsName: ```<gml:Point srsName="WGS84(DD)" srsDimension="2">```

**Comment by bartvde** [comment]
The ones that work look good: ```<gml:Point srsName="http://www.opengis.net/gml/srs/epsg.xml#4326" srsDimension="2">```

**Comment by hishamkaram** [comment]
thank you,  you are right
