### ISSUE TITLE
Labels not shown when features are selected

### ISSUE THREAD

**Issue by volaya** [boundlessgeo/sdk#442]
[webapp.zip](https://github.com/boundlessgeo/sdk/files/912952/webapp.zip)
If a feature is selected, the corresponding label vanishes.

Attached a sample app that reproduces this wrong behaviour

**Comment by bartvde** [comment]
I see what you mean, but I don't see an easy way to achieve this, will need to think a bit more about it

**Comment by bartvde** [comment]
Closing 1.x related tickets for now, since they are unlikely to be worked on
