### ISSUE TITLE
API docs missing in docs directory.

### ISSUE THREAD

**Issue by DrewRay** [boundlessgeo/sdk#446]
a bunch of 404's if you try to link to the API docs in the master repo from the https://github.com/boundlessgeo/sdk/blob/master/docs/SUMMARY.md page.  they all seem to be present in the gh-pages branch under a different directory and also under the icon-tooltips branch (1k+ commits old).

**Comment by bartvde** [comment]
it is generated content, not stored in github for obvious reasons. What is your use case? If you want to browse docs locally make sure to generate the docs with ```npm run docs```

**Comment by bartvde** [comment]
You can also serve the gitbook server locally with ```npm run serve:gitbook```

**Comment by bartvde** [comment]
If you want to link to docs, use the online version instead: https://boundlessgeo.github.io/sdk/book/index.html

**Comment by DrewRay** [comment]
should the master branch have the docs remaining there updated to push to the online book? https://boundlessgeo.github.io/sdk/book/index.html

**Comment by bartvde** [comment]
they are pushed online on every commit to master

**Comment by DrewRay** [comment]
i see how they are generated now, (via generate-api-doc.js) thanks.  as an aside it might make sense to update the readme.md to direct people to use the book instead of try navigating the repo directly since the sub-doc are not checked in

**Comment by bartvde** [comment]
good point, will add a not to the README
