### ISSUE TITLE
SDK Ver 1.0.0

### ISSUE THREAD

**Issue by kratosmat** [boundlessgeo/sdk#480]
Hi all,
I am newbie on boundlessgeo and I trying to develop an application based on it.
Using the tutorial I am using version 0.10.0 of the sdk but I would use the last stable version (1.0.0).

How can I upgrade my application dependecies?

Thanks a lot,
Matteo.

**Comment by bartvde** [comment]
If you follow the latest tutorial you should get 1.0.0 https://boundlessgeo.github.io/sdk/book/tutorial.html

```
npm install -g @boundlessgeo/sdk-generator
web-sdk /tmp/foo
```

package.json has:

```
  "dependencies": {
    "@boundlessgeo/sdk": "1.0.0",
```

**Comment by hishamkaram** [comment]
@bartvde  please update [npm version](https://www.npmjs.com/package/boundless-sdk)

**Comment by bartvde** [comment]
@hishamkaram that package is deprecated use https://www.npmjs.com/package/@boundlessgeo/sdk instead

let me verify if I deprecated it actually

**Comment by bartvde** [comment]
yeah see the WARN:

```npm WARN deprecated boundless-sdk@0.10.32: Use @boundlessgeo/sdk instead```

**Comment by hishamkaram** [comment]
@bartvde thanks
