### ISSUE TITLE
WFST add/edit feature Field Validation!!

### ISSUE THREAD

**Issue by hishamkaram** [boundlessgeo/sdk#565]
I am using WFS-T component to add new features to my layer in geoserver (zip code , address, ...)
by fault user inserted a character in zip code which is an integer field . when user click add button no validation on field type ,  the WFST Request return exception error parsing string and no message shown to user about the error

**note :** I am using the latest version

**Comment by bartvde** [comment]
Right we currently have no client-side validation

**Comment by bartvde** [comment]
Closing 1.x related tickets for now, since they are unlikely to be worked on
