### ISSUE TITLE
Zoom on selection feature table 3d 

### ISSUE THREAD

**Issue by kratosmat** [boundlessgeo/sdk#692]
Hi, 
It seems that there is a bug when zoom on selection from feature table if the layer is multi line or multi polygon and srs dimension is 3.

After an analysis I found a bug on openlayers that was fixed in 4.3.4.
https://github.com/openlayers/openlayers/issues/6990
Is an upgrade foreseen?

**Comment by bartvde** [comment]
you mean releasing a new version of sdk that has the openlayers dependency set to 4.3.4?

I assume you are using SDK 1.x right?
