### ISSUE TITLE
Support for views parameter in WMS/WFS

### ISSUE THREAD

**Issue by francbartoli** [boundlessgeo/sdk#698]
Hi,
I'm wondering if somehow that functionality is already supported or is in the roadmap. Also in case of negative response what would be the best path to add it?

**Comment by bartvde** [comment]
can you be more specific of the workflow? Like in the ol TileWMS source you can already set params yourself. You mean whether or not things like the FeatureTable use that same param in the WFS requests?

**Comment by francbartoli** [comment]
- Case TileWMS: Suppose I want to load a layer which has been defined by a parametric SQL view like [here](https://boundlessgeo.com/2015/03/support-story-getting-sql-views/). Can I create the instance of LayerList in order to have for a specific layer this sort of WMS request:

```
http://apps.opengeo.org/geoserver/wms?FORMAT=image/png&TRANSPARENT=TRUE&
LAYERS=opengeo:geonames,opengeo:geonames&
STYLES=point,heatmap&SERVICE=WMS&VERSION=1.1.1&
REQUEST=GetMap&SRS=EPSG:900913&
VIEWPARAMS=word:canyon&
BBOX=-16077730,2576500,-6186167,7155384&
WIDTH=2022&HEIGHT=936
```

- Case FeatureTable: as you guessed having a filtered instance of FeatureTable by the same parameter passed in a WFS request

**Comment by bartvde** [comment]
Yeah when you define your ol TileWMS source you can pass additional params

I haven't checked as yet if they are taken into account by the WFS code, but if they haven't a fix would not be difficult

**Comment by bartvde** [comment]
Btw are we talking about SDK 1.x or 2.x here?

**Comment by francbartoli** [comment]
Master so I'd say 2.x. Thanks for pointing that out!

**Comment by bartvde** [comment]
ok in master you just pass on the complete WMS GetMap request to the MapBox style GL JSON, so you can add whatever param you want there
