### ISSUE TITLE
Plans for other sources/formats (e.g., ESRI REST Services)

### ISSUE THREAD

**Issue by brambow** [boundlessgeo/sdk#736]
Are there any plans to add support for other sources/formats like ArcGIS REST Services/ESRIJson?

I was looking through /components/map.js to see how other sources and formats were configured to see if I could implement it, but I'm not even sure where something like ArcGIS Feature Services/ESRIJson would fit into the Mapbox style spec, where the options seem to be 'geojson' or 'vector' (for vector tiles).

Would it make more sense to use other tools to convert ESRI services to geojson, or is there a way that these sources/formats can be built into the SDK too?

**Comment by bartvde** [comment]
I think it would make sense, we did an extension for WFS as well to the mapbox spec. I don't know of any immediate plans, but I will bring it up because it probably aligns with our goals

**Comment by brambow** [comment]
Great - thank you.  I may try to hack around at it and research the WFS extension some.

And although ESRI types would be my priority, I was thinking that this general request would apply to other OL formats as well - (GPX, KML).  Right now I use Mapbox's togeojson library to just convert GPX and KML files to geojson for use in SDK apps.  Would there be any advantage to "native" implementations with the built in ol formats over this approach?

**Comment by bartvde** [comment]
The conversion needs to be done anyway, I don't think it really matters where it is done. Except for the case of ArcGIS REST Feature Service, where the protocol and format are more tied together, in that case it would need to be done in SDK I think

**Comment by bartvde** [comment]
Recently we added some support for ArcGIS REST: feature info (query) support for map click and support for EsriJSON through feature services: https://sdk.boundlessgeo.com/featureservice/index.html#x=-93.00000&y=45.00000&z=2&r=0
