### ISSUE TITLE
No sprite causes WFS to ignore style

### ISSUE THREAD

**Issue by blyefd** [boundlessgeo/sdk#778]
Having trouble setting a style for a WFS layer.
After debugging, I've narrowed it down to:
https://github.com/boundlessgeo/sdk/blob/94a1f1a60f7ffc68a61394c643882296158854cd/src/components/map.js#L789-L791

It really seems that it should be `spriteLayers.length !== 0` based on the logic above in the function.
Changing it to `!==`  fixes my problem but want double check in case I don't understand the logic.

thanks

**Comment by bartvde** [comment]
No this logic is correct, it should only apply the style function if it's not an animated sprite (see the https://sdk.boundlessgeo.com/sprite-animation/index.html example).

In another ticket you said you resorted to creating your own vector source, could that have anything do with it? Can you show some more of your code?

**Comment by blyefd** [comment]
Hi.
I just realized that I was trying to use OL styles and not Mapbox styles.  It works now that I changed it to `type: 'fill', paint: { ...`
Now that I patched the sdk to add request headers, I've gone back to using `SdkMapActions.addWfsSource...`

**Comment by bartvde** [comment]
ah cool, so we can close this ticket and leave the other one open as an enhancement ticket for adding request headers? Are you able to create a PR for this?

**Comment by blyefd** [comment]
👍
