### ISSUE TITLE
Popup component depends on Font-Awesome

### ISSUE THREAD

**Issue by brambow** [boundlessgeo/sdk#788]
Closable popups appear to depend on the font-awesome css library.  See [Line 57](https://github.com/boundlessgeo/sdk/blob/486a86dfa8fd0ddbc780eccc7a241ed8f1b0db27/src/components/map/popup.js#L57) 

`className="sdk-popup-closer fa fa-times"`

Might be a good idea to drop that dependency, since it's the only place in the project it's used (aside from the examples), and you're only using it for an 'X' character.  

It would be even better if that part was customizable/configurable.  For example, I'm building an app with SDK and Semantic UI, which already has icons built in, so it would be good to be able to use their X icon.

**Comment by bartvde** [comment]
Agreed
