### ISSUE TITLE
minZoom level for map?

### ISSUE THREAD

**Issue by jduncanRadBlue** [boundlessgeo/sdk#799]
This is a question about zoom levels on the map.  I know how to set the minzoom level on an open layers map by passing in minZoom and maxZoom to the view but its not immediatly obvious to me how to set it with boundless sdk.  I tried using the updateView and passing it in that way, as it is done in one of the examples, but it doesn't seem to stop the map from being able to zoom out.  Basically what it happening, when i zoom out, the map zooms so far out that the map gets really small and only takes up about 1/2 the webpage, and the world is shown three times. 
Is there a way to stop the zoom out from happening past a certain zoom level?
Thanks!

**Comment by bartvde** [comment]
as far as I can see the mapbox style spec does not provide this?

https://www.mapbox.com/mapbox-gl-js/style-spec/

**Comment by bartvde** [comment]
they only provide it at the source level it seems

**Comment by jduncanRadBlue** [comment]
Thanks @bartvde !

I thought the SdkMap component was using openlayers?

**Comment by bartvde** [comment]
It is, but we use the mapbox style spec for configuration

**Comment by jduncanRadBlue** [comment]
I saw that the zoom-slider contains a min and max zoom, so I incorporated that into my map.  The min and max zoom works well with that, but if I zoom in and out on the map using the mouse, it allows the min and max zoom levels for the slider to be overridden.  This seems like it is a bug?
Are there any plans to incorporate min/max zoom levels into the map view?
We are trying to integrate boundless sdk into an existing application, and this is critical functionality.  Thanks!

**Comment by bartvde** [comment]
okay so you are asking for a prop of the map component to control the minZoom right? I think I can cook up a quick PR that does that.

**Comment by bartvde** [comment]
@jduncanRadBlue can you see if #800 works for you? If so I'll add some unit tests to cover it.

**Comment by brambow** [comment]
Does this still work in 2.3.3?  I'm setting the metadata when the map component mounts, and verifying it's in the redux store, but it doesn't affect the overall map zoom level constraints.

`    this.props.updateMetadata({
      'bnd:minzoom': 4,
      'bnd:maxzoom': 18
    });
`

Notice in image below how the map zoom level is 0 even though metadata is set for 4 to be the minzoom.

![image](https://user-images.githubusercontent.com/6227786/37795968-5bae6adc-2dec-11e8-9497-8a040fdf0154.png)

**Comment by brambow** [comment]
calling updateMetadata in componentWillMount instead of componentDidMount seems to fix my problem.

**Comment by bartvde** [comment]
![selection_554](https://user-images.githubusercontent.com/319678/37817340-c417e528-2e76-11e8-9fe3-088785cbfabc.png)

Right since this is the React lifecycle, and we configure the map here:

```
  componentDidMount() {
    // put the map into the DOM
    this.configureMap();
  }
```

that makes sense. You can also use the constructor.

**Comment by brambow** [comment]
Yes, but what I'm pointing out is that calling updateMetadata to set map zoom constraints has no effect if done in componentDidMount.  It sets the redux store but has no effect on the actual zoom levels.  It only works in constructor or componentWillMount.  

All my other map actions like setView, addLayer etc work in componentDidMount like you mention.

**Comment by bartvde** [comment]
it's because we only set minZoom maxZoom on the view etc. when it's created https://github.com/boundlessgeo/sdk/blob/master/src/components/map.js#L1457

There is no code to dynamically change the view if someone dispatches that metadata change after the map has been created

**Comment by bartvde** [comment]
that code could be added though theoretically

**Comment by brambow** [comment]
Thanks.  It's not an issue.  I was really just pointing this out in case other people experienced the same behavior and wondered what was happening.  As always, this project is great.
