### ISSUE TITLE
"Deselect" features event?

### ISSUE THREAD

**Issue by brambow** [boundlessgeo/sdk#802]
This might be more of a use question rather than a code issue:

I'm building a map that has selection interactivity.  As I select features (holding shift to add to selection), I'm populating an array of selected features.  When I click the map, and a feature isn't present, the selection style disappears.  I'm lost on how to go about triggering an emptying of my selected features array when the # of selected features on the map is zero.

Is there a recommended way to go about this?

In the openlayers documentation I see that the Select interaction has a [getFeatures method](http://openlayers.org/en/latest/apidoc/ol.interaction.Select.html#getFeatures), which seems like it'd be better than my method of creating an array.  Is it possible to use this in the context of an SDK map?

**Comment by bartvde** [comment]
So you mean an action to programmatically deselect all selected features? I'm probably not understanding your use case correctly, maybe it helps if you can show some code or an example?

**Comment by brambow** [comment]
Sorry for not being clear.  

So here's a function I'm firing on the 'onFeatureSelected' event of the map.  It simply pushes the selected feature to an array.  I'm populating that array so I can perform tasks against selected features.  Let's say I want to run a buffer (via turf) just against the selected features.  So far I'm good with all that.

```  
selectFeature = (map, sourceName, feature) => {
    console.log(`Feature with ID ${feature.properties.id} selected.`);
    selectedFeatures.push(feature);
    console.log(selectedFeatures); //need to find way to clear selectedFeatures array on "unselect"
 };
```

Now let's say I click the map where there isn't a feature.  The behavior is that all selected features clear off the map.  But my array is still populated with the previously selected features.  There isn't a 'onFeaturesDeselected' property/event for the map, so I'm wondering how I can go about clearing that array of selected features.

Alternatively, is there a way to prevent a map click (that doesn't hit a feature) from deselected everything?  Then I could wire up a button to clear the selected features and array at the same time.

If you still need an example, I'll try to get one up this afternoon.

**Comment by bartvde** [comment]
thanks @brambow the issue is clear now, I need to think a bit more about possible solutions

**Comment by bartvde** [comment]
this actually looks like a bug to me, I will work on a fix soon

**Comment by bartvde** [comment]
@brambow can you see if #804 works for you?
Please note that the callback onFeatureSelected now gets a collection of features, and there is a new callback onFeatureDeselected. The modified draw example should have all the info.

**Comment by brambow** [comment]
Yes, that works.  Pretty much exactly what I was hoping for.  Thank you!

**Comment by brambow** [comment]
@bartvde I've been using the SDK npm package in my application.  Until this PR gets merged and released, what's the best way to use this change?

**Comment by bartvde** [comment]
you would need to clone the sdk repo from github, run npm i and npm run dist and then use npm link in the dist subdirectory
then in your app you link with ```npm link @boundlessgeo/sdk```

not trivial though

**Comment by bartvde** [comment]
I will see if I can get a quick review on my PR
