### ISSUE TITLE
An alternative to ejecting for building production assets.

### ISSUE THREAD

**Issue by brambow** [boundlessgeo/sdk#822]
The documentation for Boundless SDK suggests that, if using create-react-app, we have to eject in order to build the production assets.  

I felt that ejecting in order to change one-line in the webpack config _and_ losing CRA's hot-reloading on the dev server was overkill.  I'd like to share an alternative method I use to avoid ejecting.

Instead I forked create-react-app, and edited the react-scripts webpack config file so that

` include: paths.appSrc,` was changed to `include: [paths.appSrc, paths.appNodeModules],`

Then I pointed my Boundless SDK project.json to my custom react-scripts.  That's it!  No need to install webpack-cli, no need to disable hot-reloading and setup a watch operation.  Now my builds work as expected.

I followed the general instructions found in this [Medium article](https://medium.com/@denis.zhbankov/maintaining-a-fork-of-create-react-app-as-an-alternative-to-ejecting-c555e8eb2b63)

This feels much easier/cleaner than the suggestion to eject.  Perhaps Boundless would want to consider doing this and publishing a custom 'sdk-react-scripts' npm package for people that are turned off by ejecting but also not up for doing this themselves.

**Comment by bartvde** [comment]
This is a good point, and I've also contemplated forking create-react-app in the past, so I will hopefully look into this approach soon.

**Comment by bartvde** [comment]
With the latest create-react-app the eject step is not needed anymore, getting started guide has been updated
