### ISSUE TITLE
setView map property

### ISSUE THREAD

**Issue by brambow** [boundlessgeo/sdk#833]
The docs say that the map component has a property called 'setView' that is the callback function for setView, trigged on the map's 'moveend' event; however, it doesn't seem to work for me.

![image](https://user-images.githubusercontent.com/6227786/36514755-1032618a-1744-11e8-9bea-ae46bd181868.png)

I modified the basic example to demonstrate this, by adding the following around [line 185](https://github.com/boundlessgeo/sdk/blob/master/examples/basic/app.js#L185):

```
  const handleSetView = () => {
    console.log('moveend');
  };

  const handleClick = () => {
    console.log('clicked');
  };

  // place the map on the page.
  ReactDOM.render(
    <Provider store={store}>
      <RendererSwitch setView={handleSetView} onClick={handleClick}>
        <SdkScaleLine />
        <SdkMousePosition
          style={{
            position: 'absolute',
            top: 20,
            right: 12,
            zIndex: 1,
            width: '5em'
          }}
        />
        <SdkZoomControl />
        <SdkZoomSlider />
      </RendererSwitch>
    </Provider>,
    document.getElementById('map')
  );
```
Demonstration: https://github.com/cartolab-gis/sdk/blob/set-view-bug/examples/basic/app.js

The onClick callback works as expected, but there is no console message when I change the view of the map.

**Comment by bartvde** [comment]
yeah the docs are wrong here, we need to suppress those props from the documentation, as they are populated by redux

what is it you want to achieve?

**Comment by bartvde** [comment]
You should be able to subscribe a listener to the store instead and look for the ```MAP_SET_VIEW``` type actions instead and do something there, see also: https://egghead.io/lessons/javascript-redux-wrapping-dispatch-to-log-actions

**Comment by brambow** [comment]
Okay, thanks.  I'm trying to subscribe to that event so I can wait and apply a bbox query to a REST endpoint that sends too much data otherwise.  Good advice on subscribing to the store.  Thanks!

**Comment by bartvde** [comment]
Closing this one @brambow let me know if you can't get it to work by reopening if needed
