### ISSUE TITLE
MAP.REMOVE_FEATURES matches everything if filter is undefined

### ISSUE THREAD

**Issue by timotgl** [boundlessgeo/sdk#840]
According to https://sdk.boundlessgeo.com/docs/module-actions_map.html `removeFeatures(sourceName, filter)` will remove everything that matches the provided filter. However, not prodiving a filter at all seems to result in a match function expression that kicks out everything: https://github.com/boundlessgeo/sdk/blob/master/src/reducers/map.js#L551

We're actually using `removeFeatures` currently because of that behavior, but the documentation does not suggest that it should work like that. I'd expect a missing filter to not match and delete anything.

**Comment by bartvde** [comment]
Right, we are also using it that way ourselves. So we should probably update the docs ;-)
