### ISSUE TITLE
./node_modules/@boundlessgeo/sdk/components/map.js Error

### ISSUE THREAD

**Issue by dustinturp** [boundlessgeo/sdk#871]
I am following the instructions on the  [Documentation] (https://sdk.boundlessgeo.com/docs/) page of the SDK site.  I installed SDK through `yarn add @boundlessgeo/sdk`. 

Full error message: 

Module not found: Can't resolve 'mapbox-to-ol-style' in '/Users/dustinturpin/Documents/Boundless/repp/map_show_and_tell/practice2/sdk-starter/node_modules/@boundlessgeo/sdk/components'

Messing with more stuff next error message:
./node_modules/@boundlessgeo/sdk/components/map.js
Module not found: Can't resolve 'mapbox-to-ol-style' in '/Users/dustinturpin/Documents/Boundless/repp/map_show_and_tell/practice2/sdk-starter/node_modules/@boundlessgeo/sdk/components'

I think there are issues with Mapbox Styles when I commented some of them out.

**Comment by NadiaCop7** [comment]
I too have had the same error message, but have previously been able to run a dev build using 'yarn start' successfully.

When comparing package.json I note that my functional Boundless sdk map uses "ol-mapbox-style": "^2.10.1" and the sdk map that gets this error message uses "ol-mapbox-style": "^2.11.2"

**Comment by theduckylittle** [comment]
Try the latest 2.3.9 package. There were changes to ol-mapbox-style and mapbox-to-ol-style which happened recently that caused breaking changes.

**Comment by dustinturp** [comment]
Sorry for the delay on this. Yep everything is working as instructed on the Docs. Thanks!
