### ISSUE TITLE
OSM contribution is missing by default in the info box of a new SDK app.

### ISSUE THREAD

**Issue by dustinturp** [boundlessgeo/sdk#885]
"© OpenStreetMap contributors" need to be added into the infobox by default. 
https://www.openstreetmap.org/copyright
It is not seen when ran locally. Not sure about running a production build.

**Comment by dustinturp** [comment]
When I build an app from the getting started guide "© OpenStreetMap contributors" does not show up in the map in the info bar it is blank by default. It does show up in the examples on the SDK site. 

Is the intent that the SDK user would add in `© OpenStreetMap contributors` on their own? We may need to add that to the docs or add it in by default.

**Comment by bartvde** [comment]
the getting started guide should be updated to use addOsmSource instead, like the examples do. Any chance you can do a PR? If not I’ll do it tomorrow

**Comment by dustinturp** [comment]
Will do. I will test it out.

**Comment by dustinturp** [comment]
Closing issue fixed in PR https://github.com/boundlessgeo/sdk/pull/886
