### ISSUE TITLE
Getting Started 

### ISSUE THREAD

**Issue by aliasmrchips** [boundlessgeo/sdk#895]
Following the current directions at https://sdk.boundlessgeo.com/docs/ leads to this error:
```
{
  "status": 1,
  "file": "/home/aliasmrchips/sdk-starter/src/App.scss",
  "line": 1,
  "column": 1,
  "message": "File to import not found or unreadable: @boundlessgeo/sdk/stylesheet/sdk.scss.",
  "formatted": "Error: File to import not found or unreadable: @boundlessgeo/sdk/stylesheet/sdk.scss.\n        on line 1 of src/App.scss\n>> @import \"@boundlessgeo/sdk/stylesheet/sdk.scss\";\n\n   ^\n"
}
```
following the step adding the sdk scss file to App.scss
```
@import "@boundlessgeo/sdk/stylesheet/sdk.scss";
```
Repeated on Mac and Ubuntu

**Comment by aliasmrchips** [comment]
FWIW, in order to get the "Getting Started" guide to work, I had to check out and build the sdk (option B for installing). This required installing cairo in order to install node-canvas; `brew install cairo` on Mac and `sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev` on Ubuntu. Then I had to `yarn add ol-mapbox-style@2.11.2` to rollback from a v3 beta release.

**Comment by bartvde** [comment]
thanks for your feedback @aliasmrchips I am going to run to the getting started myself again and will update where needed

**Comment by aliasmrchips** [comment]
I retried the "Getting Started" with the updates and it worked like a charm. Thanks!

**Comment by bartvde** [comment]
thanks for confirming @aliasmrchips
