### ISSUE TITLE
Getting the Map Extent

### ISSUE THREAD

**Issue by jamescrowley321** [boundlessgeo/sdk#960]
Hello,

What is the idiomatic way to get the map extent? I am looking to optimize WMS/WFS calls to GeoServer by passing in the current viewport extent. When I used OpenLayers directly, I was able to do this, however, I am not seeing a surface API in the SDK that exposes that functionality. Is there a way to do this or will I need to manually implement this ability?

Thanks

**Comment by bartvde** [comment]
if you include the mapinfo reducer, it has extent as property in the state tree

**Comment by jamescrowley321** [comment]
Thanks.
