### ISSUE TITLE
Define style for a single feature

### ISSUE THREAD

**Issue by Adrien-Atmosphere** [boundlessgeo/sdk#965]
Hello.

As far as I understand, the styling of geometries is defined by layer. For instance, in the multigeometry example, there is a style for points, another for lines and a last one for polygons.

Would it be possible to manage different styles per feature in a common layer ?

**Comment by bartvde** [comment]
you can achieve this with data driven styles, see e.g.: https://docs.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/

**Comment by Adrien-Atmosphere** [comment]
Thanks for the answer.

**Comment by wnordmann** [comment]
Issue has been resolved, marking closed
